### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dekvas** [TrattMods/LiterallyChunkLoader#17] opened 2023-01-15 08:53 UTC
Hi! I tried to run your mod on Minecraft 1.19.3 
Version of fabric 0.14.12, fabric api mod - 0.69.1. The game crashes every time it starts. There are no other mods besides this one. Any ideas? Tell me how I could help solve the problem. Thank you in advance.
>
[crash-2023-01-15_14.52.57-client.txt](https://github.com/TrattMods/LiterallyChunkLoader/files/10419779/crash-2023-01-15_14.52.57-client.txt)

**Comment by dekvas** [comment] 2023-01-15 09:06
Okay, I read cursedforge and thought the problem might be in java's version. I tried using versions 17, 18 and 19, but the result is still the same.

**Comment by tratteo** [comment] 2023-01-20 17:59
Closed as duplicate of #16

**Closed by tratteo** 2023-01-20 17:59 UTC

**Comment by dekvas** [comment] 2023-01-21 16:43
@tratteo OOOOOOOOOOOO thank you so much, dude. You're really cool
